version: "3"
   
services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  app:
    build: .
    command: npm start
    volumes:
      - .:/app
      - /app/dist
      - /app/node_modules
    ports:
      - "127.0.0.1:4000:4000"
    depends_on:
      - db
