version: "3"
   
services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  app:
    build: .
    command: bash -c "npm run sync && npm run dev"
    volumes:
      - .:/app
      - /app/.next
      - /app/node_modules
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - db
