version: "3"

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile.server
    command: bash -c "npm run sync && npm start"
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:

volumes:
  pgdata:
