version: "3"
   
services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
  redis:
    image: redis:latest
    restart: unless-stopped
  app:
    image: puja-server-test_app
    build: .
    restart: unless-stopped
    command: bash -c "npm run sync && npm run dev"
    depends_on:
      - db
      - redis
  worker:
    image: puja-server-test_app
    restart: unless-stopped
    command: npm run dev-worker
    depends_on:
      - db
      - redis
