version: "3"

services:
  db:
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    volumes:
      - redis:/var/lib/redis
  app:
    image: puja-server-test_production-app
    build:
      context: .
      dockerfile: Dockerfile.production
    command: bash -c "npm run sync && npm start"
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:3000:3000"
  worker:
    image: puja-server-test_production-app
    command: npm run worker
    environment:
      DB_PASSWORD: ${DB_PASSWORD}

volumes:
  pgdata:
  redis:
